### ISSUE TITLE
update to .NET 7.0

### ISSUE THREAD

**Issue by omid-ahmadpour** [omid-ahmadpour/Ocelot.Provider.SqlServer#8]

**Comment by alazeemlearn** [comment]
Hy @VahidFarahmandian  I try Ocelot Provider SqlServer. Its work. But I try with Rate Limit doesnot work. This my Route column data `{
  "DownstreamPathTemplate": "/weatherforecast",
  "DownstreamScheme": "https",
  "DownstreamHostAndPorts": [
    {
      "Host": "localhost",
      "Port": 7172
    }
  ],
  "UpstreamPathTemplate": "/gatewaycheck",
  "UpstreamHttpMethod": [
    "Get"
  ],
  "RateLimitOptions": {
    "ClientWhitelist": [],
    "EnableRateLimiting": true,
    "Period": "3600s",
    "PeriodTimespan": 2,
    "Limit": 1
  }
}`   **How to achieve?**

**Comment by VahidFarahmandian** [comment]
> Hy @VahidFarahmandian I try Ocelot Provider SqlServer. Its work. But I try with Rate Limit doesnot work. This my Route column data `{ "DownstreamPathTemplate": "/weatherforecast", "DownstreamScheme": "https", "DownstreamHostAndPorts": [ { "Host": "localhost", "Port": 7172 } ], "UpstreamPathTemplate": "/gatewaycheck", "UpstreamHttpMethod": [ "Get" ], "RateLimitOptions": { "ClientWhitelist": [], "EnableRateLimiting": true, "Period": "3600s", "PeriodTimespan": 2, "Limit": 1 } }` **How to achieve?**

Please refer to the following issue:
https://github.com/ThreeMammals/Ocelot/issues/1598

**Comment by VahidFarahmandian** [comment]
> Hy @VahidFarahmandian I try Ocelot Provider SqlServer. Its work. But I try with Rate Limit doesnot work. This my Route column data `{ "DownstreamPathTemplate": "/weatherforecast", "DownstreamScheme": "https", "DownstreamHostAndPorts": [ { "Host": "localhost", "Port": 7172 } ], "UpstreamPathTemplate": "/gatewaycheck", "UpstreamHttpMethod": [ "Get" ], "RateLimitOptions": { "ClientWhitelist": [], "EnableRateLimiting": true, "Period": "3600s", "PeriodTimespan": 2, "Limit": 1 } }` **How to achieve?**

Also it seems that mapping `RateLimitOptions` section has been missed in code(Just a guess). Check the `Get` method inside the `SqlServerFileConfigurationRepository` class.
https://github.com/omid-ahmadpour/Ocelot.Provider.SqlServer/blob/7aae586eb846a882cf14e5ffd3d46cdd667e9c81/Ocelot.Provider.SqlServer/Repository/SqlServerFileConfigurationRepository.cs#L34

@omid-ahmadpour

**Comment by alazeemlearn** [comment]
`"RateLimitOptions"` instead of this I code `"RateLimitRule"`. That's my mistake. I declared here correctly. Mistakes in my Config

**Comment by omid-ahmadpour** [comment]
It's great to hear that you found the library useful! Mistakes happen to everyone. It seems like you've already identified the issue with your code.
If you have any more questions or need further clarification, feel free to ask. I'm here to help! 😊

**Comment by omid-ahmadpour** [comment]
As there have been no further responses on this issue, it will now be closed.
