### ISSUE TITLE
How to store Ocelot Logging history to SQL

### ISSUE THREAD

**Issue by alazeemlearn** [omid-ahmadpour/Ocelot.Provider.SqlServer#9]
I like to store Ocelot  Logging history to SQL locally. Include RequestId. How to achieve this ? I get my Logging history in my Console.
`Hosting environment: Development
Content root path: D:\Al Azeem\OneDrive - MGUKDD\Attachments\Pratices\Gateway
Now listening on: https://localhost:7095
Now listening on: http://localhost:5149
Application started. Press Ctrl+C to shut down.
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET https://localhost:7095/weatherforecast - -
warn: Ocelot.DownstreamRouteFinder.Middleware.DownstreamRouteFinderMiddleware[0]
      requestId: 0HN0526GC2DD0:00000001, previousRequestId: No PreviousRequestId, message: 'DownstreamRouteFinderMiddleware setting pipeline errors. IDownstreamRouteFinder returned Error Code: UnableToFindDownstreamRouteError Message: Failed to match Route configuration for upstream path: /weatherforecast, verb: GET.'
warn: Ocelot.Responder.Middleware.ResponderMiddleware[0]
      requestId: 0HN0526GC2DD0:00000001, previousRequestId: No PreviousRequestId, message: 'Error Code: UnableToFindDownstreamRouteError Message: Failed to match Route configuration for upstream path: /weatherforecast, verb: GET. errors found in ResponderMiddleware. Setting error response for request path:/weatherforecast, request method: GET'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 GET https://localhost:7095/weatherforecast - - - 404 0 - 255.3270ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET https://localhost:7095/gatewaycheck - -
info: Ocelot.RateLimit.Middleware.ClientRateLimitMiddleware[0]
      requestId: 0HN0526GC2DD0:00000003, previousRequestId: No PreviousRequestId, message: 'EndpointRateLimiting is not enabled for /weatherforecast'
info: Ocelot.Authentication.Middleware.AuthenticationMiddleware[0]
      requestId: 0HN0526GC2DD0:00000003, previousRequestId: No PreviousRequestId, message: 'No authentication needed for /gatewaycheck'
info: Ocelot.Authorization.Middleware.AuthorizationMiddleware[0]
      requestId: 0HN0526GC2DD0:00000003, previousRequestId: No PreviousRequestId, message: '/weatherforecast route does not require user to be authorized'
warn: Ocelot.Requester.Middleware.HttpRequesterMiddleware[0]
      requestId: 0HN0526GC2DD0:00000003, previousRequestId: No PreviousRequestId, message: '500 (Internal Server Error) status code, request uri: https://localhost:7094/weatherforecast'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 GET https://localhost:7095/gatewaycheck - - - 500 48 text/plain;+charset=utf-8 247.8273ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET https://localhost:7095/favicon.ico - -
warn: Ocelot.DownstreamRouteFinder.Middleware.DownstreamRouteFinderMiddleware[0]
      requestId: 0HN0526GC2DD0:00000005, previousRequestId: No PreviousRequestId, message: 'DownstreamRouteFinderMiddleware setting pipeline errors. IDownstreamRouteFinder returned Error Code: UnableToFindDownstreamRouteError Message: Failed to match Route configuration for upstream path: /favicon.ico, verb: GET.'
warn: Ocelot.Responder.Middleware.ResponderMiddleware[0]
      requestId: 0HN0526GC2DD0:00000005, previousRequestId: No PreviousRequestId, message: 'Error Code: UnableToFindDownstreamRouteError Message: Failed to match Route configuration for upstream path: /favicon.ico, verb: GET. errors found in ResponderMiddleware. Setting error response for request path:/favicon.ico, request method: GET'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 GET https://localhost:7095/favicon.ico - - - 404 0 - 0.6857ms

`

**Comment by omid-ahmadpour** [comment]
Hi @alazeemlearn,
To implement logging using the Serilog library, follow these steps:
Install the necessary packages:

Install-Package Serilog
Install-Package Serilog.AspNetCore
Install-Package Serilog.Sinks.MSSqlServer
Install-Package Serilog.Settings.Configuration

Add the following code to your application builder:

public static IWebHost BuildWebHost(string[] args) =>
    WebHost.CreateDefaultBuilder(args)
        .UseSerilog((hostingContext, loggerConfiguration) => loggerConfiguration
            .ReadFrom.Configuration(hostingContext.Configuration)
            .Enrich.FromLogContext()
            .WriteTo.MSSqlServer(
                connectionString: "<YourConnectionString>",
                tableName: "Logs",
                autoCreateSqlTable: true))
        .UseStartup<Startup>()
        .Configure(app => 
        {
            app.UseSerilogRequestLogging(options => 
            {
                options.EnrichDiagnosticContext = (diagnosticContext, httpContext) => 
                {
                    diagnosticContext.Set("RequestId", httpContext.TraceIdentifier);
                };
            });
        })
        .Build();

Please confirm whether you have made these changes and share the outcome.

**Comment by alazeemlearn** [comment]
![image](https://github.com/omid-ahmadpour/Ocelot.Provider.SqlServer/assets/152181858/5d4d9c57-38e5-4be8-a04a-1137ce40e62a)
`
using System.Collections.ObjectModel;
using System.Data;
using System.IO;
using System.Net.NetworkInformation;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Hosting;
using Ocelot.DependencyInjection;
using Ocelot.Middleware;
using Ocelot.Provider.Polly;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;

using Gateway.Middleware;
using Ocelot.Logging;
using Gateway.LoggingContext;
using Ocelot.Values;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore;
using Serilog;

namespace Gateway
{
    public class Program
    {
        public static void Main(string[] args)
        {
            var builder = WebApplication.CreateBuilder(args);
            new WebHostBuilder()
                .UseKestrel()
                .UseContentRoot(Directory.GetCurrentDirectory())
                .ConfigureAppConfiguration((hostingContext, config) =>
                {
                    config
                        .SetBasePath(hostingContext.HostingEnvironment.ContentRootPath)
                        .AddJsonFile("appsettings.json", true, true)
                        .AddJsonFile($"appsettings.{hostingContext.HostingEnvironment.EnvironmentName}.json", true, true)
                        .AddJsonFile("Ocelot.json")
                        .AddEnvironmentVariables();
                })

                .ConfigureServices(s =>
                {
                    s.AddOcelot()
                    .AddSingletonDefinedAggregator<FakeDefinedAggregator>()
                    .AddPolly();
                })

                .ConfigureLogging((hostingContext, logging) =>
                {
                    logging.ClearProviders();

                    // Add Serilog configuration
                    var logger = new LoggerConfiguration()
                        .ReadFrom.Configuration(hostingContext.Configuration)
                        .Enrich.FromLogContext()
                        .WriteTo.MSSqlServer(
                            connectionString: "Your ConnectionString",
                            tableName: "Logs",
                            autoCreateSqlTable: true)
                        .CreateLogger();

                    logging.AddSerilog(logger, dispose: true);  // Use dispose: true if you want to dispose of the logger when the provider is disposed.

                    logging.AddConsole();
                })
                .UseIISIntegration()
                .Configure(app =>
                {
                    app.UseOcelot().Wait();
                    app.UseMiddleware<LoggingDbContext>();
                })
                .Build()
                .Run();
        }
    }
}`      I like to show RequestId as a separate column for better view.

**Comment by alazeemlearn** [comment]
![Screenshot (7)](https://github.com/omid-ahmadpour/Ocelot.Provider.SqlServer/assets/152181858/c0b4550e-2151-4c23-a4b5-5d11de4f6cff)
`using System.Collections.ObjectModel;
using System.Data;
using System.IO;
using System.Net.NetworkInformation;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Hosting;
using Ocelot.DependencyInjection;
using Ocelot.Middleware;
using Ocelot.Provider.Polly;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;

using Gateway.Middleware;
using Ocelot.Logging;
using Gateway.LoggingContext;
using Ocelot.Values;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore;
using Serilog;

namespace Gateway
{
    public class Program
    {
        public static void Main(string[] args)
        {
            var builder = WebApplication.CreateBuilder(args);
            new WebHostBuilder()
                .UseKestrel()
                .UseContentRoot(Directory.GetCurrentDirectory())
                .ConfigureAppConfiguration((hostingContext, config) =>
                {
                    config
                        .SetBasePath(hostingContext.HostingEnvironment.ContentRootPath)
                        .AddJsonFile("appsettings.json", true, true)
                        .AddJsonFile($"appsettings.{hostingContext.HostingEnvironment.EnvironmentName}.json", true, true)
                        .AddJsonFile("Ocelot.json")
                        .AddEnvironmentVariables();
                })

                .ConfigureServices(s =>
                {
                    s.AddOcelot()
                    .AddSingletonDefinedAggregator<FakeDefinedAggregator>()
                    .AddPolly();
                })

                .ConfigureLogging((hostingContext, logging) =>
                {
                    logging.ClearProviders();

                    // Add Serilog configuration
                    var logger = new LoggerConfiguration()
                        .ReadFrom.Configuration(hostingContext.Configuration)
                        .Enrich.FromLogContext()
                        .WriteTo.MSSqlServer(
                            connectionString: "connectionstring",
                            tableName: "Logs",
                            autoCreateSqlTable: true)
                        .CreateLogger();

                    logging.AddSerilog(logger, dispose: true);  // Use dispose: true if you want to dispose of the logger when the provider is disposed.

                    logging.AddConsole();
                })
                .UseIISIntegration()
                .Configure(app =>
                {
                    app.UseOcelot().Wait();
                    app.UseMiddleware<LoggingDbContext>();
                })
                .Build()
                .Run();
        }
    }
}`                   **I like to Show requestId as a separate column. **

**Comment by alazeemlearn** [comment]
Hi @omid-ahmadpour
 
        .ConfigureLogging((hostingContext, logging) =>
        {
            logging.ClearProviders();
           
            var logger = new LoggerConfiguration()
                .ReadFrom.Configuration(hostingContext.Configuration)
                .Enrich.FromLogContext()
                .WriteTo.MSSqlServer(
                    connectionString: "connectionstring",
                    tableName: "Logs",
                    autoCreateSqlTable: false,
                    columnOptions: new ColumnOptions
                    {
                        AdditionalColumns = new List<SqlColumn>
                        {
                            new SqlColumn { ColumnName = "RequestId", PropertyName = "RequestId" }
                           
                        }
                    })
                        .CreateLogger();
                                logging.AddSerilog(logger, dispose: true);
                                logging.AddConsole();
                    })
                    
![Screenshot (8)](https://github.com/omid-ahmadpour/Ocelot.Provider.SqlServer/assets/152181858/19c80a9d-df40-4549-8687-2be599f4dbd4)
Finally I get my Output.

**Comment by omid-ahmadpour** [comment]
Hi @alazeemlearn,
That's fantastic! I'm glad to hear that it worked for you. If you have any more questions or need further assistance in the future, don't hesitate to ask. Happy coding! 😊

**Comment by alazeemlearn** [comment]
@omid-ahmadpour Thank u bro!!!

**Comment by omid-ahmadpour** [comment]
Issue has been resolved.
